spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    password: root
    username: root
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate.format_sql: true #格式化sql


server:
  servlet:
    context-path: /chapter2-1
  port: 8033








